### ISSUE TITLE
Trimmed in the `localPreOrSuffix` normalization

### ISSUE THREAD

**Issue by vanbroup** [pkic/regions#2]
Some values get trimmed in the `localPreOrSuffix` normalization, while I have only seen this happening with diacritics for now, this is not related to the `precisNormalization` which is only used in the map generation.

For the two examples below, the source value is correct, no normalization should be applied.

```yaml
    # íregyhá
    - codes:
        iso3166-2: HU-NY
      names:
        - name: íregyhá
          sources:
            - name: iso3166-2
              languages: [hu]
              value: Nyíregyháza
```

```yaml
    # Tamil Nā
    - codes:
        iso3166-2: IN-TN
      names:
        - name: Tamil Nā
          sources:
            - name: iso3166-2
              languages: [en]
              value: Tamil Nādu
```
